# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdmiro', '0002_ingresosmeses'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesMeses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
            ],
        ),
    ]
