# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdmiro', '0003_detallesmeses'),
    ]

    operations = [
        migrations.CreateModel(
            name='agencia_asesores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='agencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('coordenadax', models.CharField(max_length=100)),
                ('coordenaday', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='asesores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='agencia_asesores',
            name='agencias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdmiro.agencias'),
        ),
        migrations.AddField(
            model_name='agencia_asesores',
            name='asesores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdmiro.asesores'),
        ),
        migrations.AddField(
            model_name='agencia_asesores',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdmiro.producto'),
        ),
    ]
