# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdmiro', '0004_auto_20180323_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencias',
            name='direccion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
