# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdmiro', '0005_agencias_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='trasacciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tra_mes', models.CharField(max_length=2)),
                ('tra_anio', models.CharField(max_length=4)),
                ('tra_valor', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='producto',
            new_name='productos',
        ),
        migrations.RemoveField(
            model_name='agencia_asesores',
            name='agencias',
        ),
        migrations.RemoveField(
            model_name='agencia_asesores',
            name='asesores',
        ),
        migrations.RemoveField(
            model_name='agencia_asesores',
            name='producto',
        ),
        migrations.DeleteModel(
            name='DetallesMeses',
        ),
        migrations.DeleteModel(
            name='IngresosMeses',
        ),
        migrations.RenameField(
            model_name='agencias',
            old_name='coordenadax',
            new_name='age_coordenadax',
        ),
        migrations.RenameField(
            model_name='agencias',
            old_name='coordenaday',
            new_name='age_coordenaday',
        ),
        migrations.RenameField(
            model_name='agencias',
            old_name='direccion',
            new_name='age_direccion',
        ),
        migrations.RenameField(
            model_name='agencias',
            old_name='nombre',
            new_name='age_nombre',
        ),
        migrations.RenameField(
            model_name='asesores',
            old_name='nombre',
            new_name='ase_apellidos',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='nombre',
            new_name='pro_nombre',
        ),
        migrations.AddField(
            model_name='asesores',
            name='ase_nombres',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asesores',
            name='id_agencias',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appdmiro.agencias'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='agencia_asesores',
        ),
        migrations.AddField(
            model_name='trasacciones',
            name='id_asesores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdmiro.asesores'),
        ),
        migrations.AddField(
            model_name='trasacciones',
            name='id_productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdmiro.productos'),
        ),
    ]
