# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appdmiro', '0007_auto_20180326_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='agencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_nombre', models.CharField(max_length=100)),
                ('age_direccion', models.CharField(max_length=100)),
                ('age_coordenadax', models.CharField(max_length=100)),
                ('age_coordenaday', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='asesores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ase_nombres', models.CharField(max_length=100)),
                ('ase_apellidos', models.CharField(max_length=100)),
                ('id_agencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdmiro.agencias')),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='trasacciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tra_mes', models.CharField(max_length=2)),
                ('tra_anio', models.CharField(max_length=4)),
                ('tra_valor', models.CharField(max_length=100)),
                ('id_asesores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdmiro.asesores')),
                ('id_productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdmiro.productos')),
            ],
        ),
    ]
