# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdmiro', '0008_agencias_asesores_productos_trasacciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asesores',
            name='id_agencias',
        ),
        migrations.RemoveField(
            model_name='trasacciones',
            name='id_asesores',
        ),
        migrations.RemoveField(
            model_name='trasacciones',
            name='id_productos',
        ),
        migrations.DeleteModel(
            name='agencias',
        ),
        migrations.DeleteModel(
            name='asesores',
        ),
        migrations.DeleteModel(
            name='productos',
        ),
        migrations.DeleteModel(
            name='trasacciones',
        ),
    ]
