# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 00:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdmiro', '0013_auto_20180327_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasacciones',
            name='tra_valor',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
